In [25]:
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer, one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, Embedding

In [26]:
doc = ['0.1','0.00056','0.0346','0.000732','47.','100.32']

In [27]:
t = Tokenizer()
t.fit_on_texts(doc)
vocab_size = 50
#encoded_docs = t.texts_to_sequences(doc)
encoded_docs = [one_hot(d, vocab_size) for d in doc]
print(encoded_docs)
#print(t.word_counts)
#print(t.document_count)
#print(t.word_index)
#print(t.word_docs)

[[7, 22], [7, 43], [7, 5], [7, 26], [27], [14, 22]]


In [20]:
#encoded_docs = t.sequences_to_matrix(doc, mode='count')
#print(encoded_docs)

In [28]:
max_lenght = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_lenght,padding = 'post')
print(padded_docs)

[[ 7 22  0  0]
 [ 7 43  0  0]
 [ 7  5  0  0]
 [ 7 26  0  0]
 [27  0  0  0]
 [14 22  0  0]]


In [ ]:
embedding_index